tunnel: grocery-manager
credentials-file: ~/.cloudflared/grocery-manager.json

ingress:
  - hostname: grocery-manager.trycloudflare.com
    service: https://localhost:5001
    originRequest:
      noTLSVerify: true
      httpHostHeader: localhost:5001
      originServerName: localhost
      connectTimeout: 30s
      keepAliveTimeout: 30s
      keepAliveConnections: 100
      proxyConnectTimeout: 30s
      proxyTLSTimeout: 10s
      proxyTCPKeepalive: 30s
      disableChunkedEncoding: false
      http2Origin: true
  - service: http_status:404 