name: Neon Database and Deployment Workflow

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
  push:
    branches:
      - neon_deploy

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    name: Setup
    outputs:
      branch: ${{ steps.branch_name.outputs.current_branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

  create_neon_branch:
    name: Create Neon Branch
    outputs:
      db_url: ${{ steps.create_neon_branch_encode.outputs.db_url }}
      db_url_with_pooler: ${{ steps.create_neon_branch_encode.outputs.db_url_with_pooler }}
    needs: setup
    if: |
      (github.event_name == 'pull_request' && (
      github.event.action == 'synchronize'
      || github.event.action == 'opened'
      || github.event.action == 'reopened'))
      || (github.event_name == 'push' && github.ref == 'refs/heads/neon_deploy')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create Neon Branch
        id: create_neon_branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch_name: ${{ github.event_name == 'pull_request' && format('preview/pr-{0}-{1}', github.event.number, needs.setup.outputs.branch) || 'neon_deploy' }}
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Run Migrations
        run: npm run migrate
        env:
          DATABASE_URL: "${{ steps.create_neon_branch.outputs.db_url_with_pooler }}"

      - name: Post Schema Diff Comment to PR
        if: github.event_name == 'pull_request'
        uses: neondatabase/schema-diff-action@v1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          compare_branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          api_key: ${{ secrets.NEON_API_KEY }}

  delete_neon_branch:
    name: Delete Neon Branch
    needs: setup
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          api_key: ${{ secrets.NEON_API_KEY }}

  deploy:
    name: Deploy to Neon
    needs: create_neon_branch
    if: github.ref == 'refs/heads/neon_deploy'
    runs-on: ubuntu-latest
    environment: production
    env:
      DATABASE_URL: ${{ needs.create_neon_branch.outputs.db_url_with_pooler }}
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm install
          npm install -D vite typescript @types/node
          npm install -g @neondatabase/cli
        
      - name: Build
        run: npm run build

      - name: Deploy to Neon
        run: |
          neonctl deploy \
            --project-id ${{ vars.NEON_PROJECT_ID }} \
            --api-key ${{ secrets.NEON_API_KEY }} \
            --branch ${{ github.ref_name }} \
            --env DATABASE_URL=${{ needs.create_neon_branch.outputs.db_url_with_pooler }} \
            --env NODE_ENV=production 